//! gRPC SnapshotQueryService — 快照完整性查询（P7 GraphIntegrityVerifier 后端）

use sqlx::PgPool;
use tonic::{Request, Response, Status};
use tracing::info;

// Generated by tonic-build from snapshot_query.proto
pub mod ocg_snapshot {
    tonic::include_proto!("ocg.snapshot_query.v1");
}
use ocg_snapshot::{
    snapshot_query_service_server::SnapshotQueryService as SqsTrait,
    CheckIntegrityRequest, CheckIntegrityResponse,
};

pub struct SnapshotQueryServiceImpl {
    pool: PgPool,
}

impl SnapshotQueryServiceImpl {
    pub fn new(pool: PgPool) -> Self { Self { pool } }
}

#[tonic::async_trait]
impl SqsTrait for SnapshotQueryServiceImpl {
    async fn check_integrity(
        &self,
        req: Request<CheckIntegrityRequest>,
    ) -> Result<Response<CheckIntegrityResponse>, Status> {
        let r = req.into_inner();
        info!(
            repo = %r.repository_name, sha = %r.base_commit_sha,
            checkpoint = %r.candidate_checkpoint_hash, gen = r.execution_generation,
            "CheckIntegrity"
        );

        let snap = sqlx::query_as::<_, SnapshotRow>(
            "SELECT s.snapshot_id::text, s.state, s.execution_generation,
                    s.candidate_checkpoint_hash, s.graph_content_hash,
                    s.node_count, s.edge_count, s.coverage_status
             FROM ofg_snapshot s
             JOIN ofg_repository r ON s.repository_id = r.repository_id
             WHERE r.name = $1 AND s.base_commit_sha = $2
               AND s.candidate_checkpoint_hash = $3
             ORDER BY s.created_at DESC LIMIT 1"
        )
        .bind(&r.repository_name).bind(&r.base_commit_sha)
        .bind(&r.candidate_checkpoint_hash)
        .fetch_optional(&self.pool).await
        .map_err(|e| { tracing::warn!("PG error: {}", e); Status::internal("database error") })?;

        let mut resp = CheckIntegrityResponse::default();

        let snap = match snap {
            Some(s) => { resp.snapshot_exists = true; s }
            None => {
                resp.error_detail = format!(
                    "no snapshot for repo={} sha={} checkpoint={}",
                    r.repository_name, r.base_commit_sha, r.candidate_checkpoint_hash
                );
                return Ok(Response::new(resp));
            }
        };

        resp.is_sealed = snap.state == "SEALED";
        resp.checkpoint_matches = snap.candidate_checkpoint_hash == r.candidate_checkpoint_hash;
        resp.generation_matches = snap.execution_generation == r.execution_generation as i64;
        let sid = snap.snapshot_id.clone();
        resp.snapshot_id = sid.clone();
        resp.graph_content_hash = snap.graph_content_hash;
        resp.node_count = snap.node_count;
        resp.edge_count = snap.edge_count;
        resp.coverage_status = snap.coverage_status;

        // Check changed files
        if !r.changed_files.is_empty() {
            let processed: Vec<String> = sqlx::query_as::<_, (String,)>(
                "SELECT f.rel_path FROM ofg_file f
                 JOIN ofg_file_version fv ON f.file_id = fv.file_id
                 WHERE fv.snapshot_id = $1::uuid AND f.rel_path = ANY($2)"
            )
            .bind(&sid).bind(&r.changed_files)
            .fetch_all(&self.pool).await
            .map_err(|e| Status::internal(format!("file query: {}", e)))?
            .into_iter().map(|(p,)| p).collect();

            resp.all_files_processed = processed.len() == r.changed_files.len();
            resp.unprocessed_files = r.changed_files.iter()
                .filter(|f| !processed.contains(f)).cloned().collect();
        } else {
            resp.all_files_processed = true;
        }

        // Check coverage
        if !r.required_passes.is_empty() {
            let covered: Vec<String> = sqlx::query_as::<_, (String,)>(
                "SELECT DISTINCT pass_name FROM ofg_pass_coverage
                 WHERE snapshot_id = $1::uuid AND pass_name = ANY($2) AND status = 'COMPLETE'"
            )
            .bind(&sid).bind(&r.required_passes)
            .fetch_all(&self.pool).await
            .map_err(|e| Status::internal(format!("coverage query: {}", e)))?
            .into_iter().map(|(p,)| p).collect();

            resp.coverage_complete = covered.len() == r.required_passes.len();
            resp.missing_passes = r.required_passes.iter()
                .filter(|p| !covered.contains(p)).cloned().collect();
        } else {
            resp.coverage_complete = true;
        }

        Ok(Response::new(resp))
    }
}

#[derive(sqlx::FromRow)]
struct SnapshotRow {
    snapshot_id: String, state: String, execution_generation: i64,
    candidate_checkpoint_hash: String, graph_content_hash: String,
    node_count: i64, edge_count: i64, coverage_status: String,
}
